# Generated by Django 5.0.3 on 2024-03-14 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfume', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accord',
            options={'ordering': ['accord']},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['note']},
        ),
    ]
