# Generated by Django 5.0.3 on 2024-03-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfume', '0002_alter_accord_options_alter_note_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfume',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='likes',
        ),
        migrations.AddField(
            model_name='perfume',
            name='rating',
            field=models.IntegerField(default=1, max_length=5),
        ),
    ]
