# Generated by Django 5.0.3 on 2024-03-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfume', '0003_remove_perfume_dislikes_remove_perfume_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='rating',
            field=models.IntegerField(default=1),
        ),
    ]
